schema_version = 2
name = "lance"
extension_config = "extension_config_vane.cmake"
build_extensions = ["parquet", "json", "icu"]
native_test_selection = "test/sql/dual_build_smoke.test"

[vane]
repository = "AstroVela/vane"
revision = "4e12994a2fed5b872a7bdb44df72c1b9c5653cdc"

[vcpkg]
repository = "microsoft/vcpkg"
revision = "84bab45d415d22042bd0b9081aea57f362da3f35"
