schema_version = 2
name = "lance"
extension_config = "extension_config_vane.cmake"
build_extensions = ["parquet", "json", "icu"]
native_test_selection = "test/sql/dual_build_smoke.test"

[vane]
repository = "AstroVela/vane"
# Vane v0.2.0.
revision = "79049f382ba6ee79d035c09cc8b5d3538e5bbe6a"

[vcpkg]
repository = "microsoft/vcpkg"
revision = "84bab45d415d22042bd0b9081aea57f362da3f35"
